In [1]:
import numpy as np

In [2]:
# Global index of local DOF
def gl_index(elem_index,local_dof):
    return elem_index + local_dof

In [3]:
# Boundary conditions
def apply_bcs(K_gl,F_gl,dof,value):
    phi = 1.0
    bignumber = 10.0**15
    K_gl[dof,dof] += bignumber*phi*phi
    F_gl[dof] += bignumber*float(value)*phi  

In [4]:
# Global stiffness matrix and mas matrix
def GlobalSystem(E,L,A,n_elem,bc1,bc2):
    
    # Element stiffness matrix and element load vector
    k_elem = E*A/L * np.array([[1.0, -1.0], [-1.0, 1.0]])
    f_elem = np.array([0.0, 0.0])

    # Global stiffness matrix and load vector
    K_gl = np.zeros((n_elem+1, n_elem+1))
    F_gl = np.zeros((n_elem+1))
    M_gl = np.zeros((n_elem+1, n_elem+1))
    # Assembly of elements
    for i_el in range(n_elem):
        for i_loc in range(2):
            i_gl = gl_index(i_el, i_loc)
            F_gl[i_gl] += f_elem[i_loc]
            for j_loc in range(2):
                j_gl = gl_index(i_el, j_loc)
                K_gl[i_gl, j_gl] += k_elem[i_loc, j_loc]

    # Boundary conditions
    apply_bcs(K_gl, F_gl, 0, bc1)
    apply_bcs(K_gl, F_gl, n_elem, bc2)

    # Approximate solution
    # uh = np.linalg.solve(K_gl, F_gl)

    return K_gl, M_gl

In [5]:
# Input parameters
# Material parameters
E = 15000.0
L = 2.0
A = 1.0
# Boundary conditions
# Velocities
bc1 = -5.0
bc2 = 5.0
# Mesh
n_elem = 2

In [6]:
# Test GetGlobalSystem function
GlobalSystem(E,L,A,n_elem,bc1,bc2)

(array([[ 1.0e+15, -7.5e+03,  0.0e+00],
        [-7.5e+03,  1.5e+04, -7.5e+03],
        [ 0.0e+00, -7.5e+03,  1.0e+15]]),
 array([-5.e+15,  0.e+00,  5.e+15]),
 array([-5.00000000e+00,  4.85063841e-16,  5.00000000e+00]))

In [7]:
# Newmark's method
def newmark(K, M, C, u0, v0, acel0, p, n_steps, dt, gamma, beta):
    #acel0 = np.matmul(np.linalg.inv(M),(p0 - C*v0 - K*u0))

    # Degrees of freedom
    dofs = K.shape[0]
    # Integration constants
    alpha = [
        1.0/(beta*dt**2.0),
        gamma/(beta*dt),
        1.0/(beta*dt),
        1.0/(2.0*beta)-1.0,
        gamma/beta-1.0,
        (gamma/beta-2.0)*dt/2.0,
        (1.0-gamma)*dt,
        gamma*dt
        ]

    # Effective stiffness matrix
    Keff = K + alpha[0]*M + alpha[1]*C
    print(Keff)
    # Keff inverse
    Kinv = np.linalg.inv(Keff)
    print(Kinv)

    # Integration
    # Vector of effective forces at time p
    pef = np.zeros((n_steps+1,dofs))
    # Vector of displacements at time u
    u = np.zeros((n_steps+1,dofs))
    u[0] = u0
    # Vector of accelerations  and velocities at time
    acel = np.zeros((n_steps+1,dofs))
    acel[0] = acel0
    v = np.zeros((n_steps+1,dofs))
    v[0] = v0
    for n in range(n_steps):
        # Vector of effective forces p
        term1 = alpha[0]*u[n] + alpha[2]*v[n] + alpha[3]*acel[n]
        term2 = alpha[1]*u[n] + alpha[4]*v[n] + alpha[5]*acel[n]
        pef[n+1] = p[n+1] + np.matmul(M,term1) + np.matmul(C,term2)
        # Vector of displacements u
        u[n+1] = np.matmul(Kinv,pef[n+1])
        # Vector of accelerations acel and velocities v 
        acel[n+1] = alpha[0]*(u[n+1]-u[n]) - alpha[2]*v[n] - alpha[3]*acel[n]
        v[n+1] = v[n] + alpha[6]*acel[n] + alpha[7]*acel[n+1]
    print(pef)  
    
    return u,v,acel

In [11]:
# Fragments sizes
def frag_size_grady(v,Gc,rho,L,t):
    # Strain rate
    strain_rate = np.zeros(t)
    strain_rate = 2.0*v[[t]]/L
    # Fragment size
    s = np.zeros(t)
    for i in range(t):
        s[[i]] = (24*Gc)/(rho*strain_rate[[i]]**2)**(1/3)
    return s

In [ ]:
# Strain rate and stress limit
strain_rate = np.zeros(n_steps)
for i in range(n_steps):
    strain_rate = 2.0*v[n_steps]/L

In [13]:
# Fragments sizes by Grady
def grady():


    return s

SyntaxError: expected ':' (1485181841.py, line 4)

In [ ]:
# Global algorithm 
# Input parameters
# Material parameters
E = 15000.0
L = 2.0
A = 1.0
Gc = 3000
# Boundary conditions
# Velocities
bc1 = -5.0
bc2 = 5.0
# Mesh
n_elem = 2
dofs = n_elem + 1
# Time steps
n_steps = 10
# Initial data
u0 = np.array([[0.02,0.02]])
v0 = np.array([[0.0,0.0]])
acel0 = np.array([[-18.0,0.0]])
p = np.zeros((n_steps+1,dofs))
# Increment of time
dt = 1
gamma = 0.5
beta = 0 
C = np.zeros((dofs,dofs))  

# Get K_gl and M_gl
K,M = GlobalSystem(E,L,A,n_elem,bc1,bc2)
# Get u,v and a
u,v,acel = newmark(K,M,C,u0,v0,acel0,p,n_steps,dt,gamma,beta)


$$
f(x) = a + b\sin (c(x +d)) 
$$

$$
f(x) = b\sin (cx) 
$$

$$
f(x) = 5000\sin (2\pi x) 
$$